### ISSUE TITLE
[chore] I can not start storybook

### ISSUE THREAD

**Issue by GrinZero** [MR-Mostafa/Viact#1]
![image](https://user-images.githubusercontent.com/70185413/184547069-804b4a8c-5558-425b-b84d-1beda7555897.png)
I don't think your dependency is completely installed

**Comment by MR-Mostafa** [comment]
@GrinZero 
Hello
Could you please describe the steps and what you did?
It was fine when I tested again

**Comment by GrinZero** [comment]
Hi～Sir
I use `npx degit https://github.com/MR-Mostafa/Viact xxx` to init the project, and use pnpm to instead of yarn.

You can try to remove the `node_modules`, `yarn.lock` and try again?

**Comment by MR-Mostafa** [comment]
> @GrinZero 

As per the `@storybook/builder-vite` docs if you're using `pnpm`, you may need to enable [shamefully-hoist](https://pnpm.io/npmrc#shamefully-hoist). ([source](https://github.com/storybookjs/builder-vite#installation))

In addition, `Viact` has been updated and the announced problem has been resolved. I recommend that you clone the latest version of the `Viact` package again.

**Comment by GrinZero** [comment]
> > @GrinZero
> 
> 根据`@storybook/builder-vite`文档，如果您使用`pnpm`，您可能需要启用[可耻的提升](https://pnpm.io/npmrc#shamefully-hoist)。（[来源](https://github.com/storybookjs/builder-vite#installation)）
> 
> 此外，`Viact`已更新并已解决已宣布的问题。我建议您`Viact`再次克隆最新版本的软件包。

Thank you. I'll try it later
